#' Adds date annotations to ggepicurve plots
#'
#' Adds extra lines at the bottom of the plot or the panel and prints date annotations for calendar-weeks, months, quarters or years.
#'
#' This function is designed to work with plots generated by [ggepicurve::ggepicurve()].
#' However any ggplot2 plot with x-scale breaks consisting of character format dates could potentially work.
#'
#'@param date_unit character string setting the unit of time for which to add the annotations.
#'@param y_percentage Numeric value specifying by which percentage of the complete Y-axis the annotations should be shifted.
#' This value will most likely need fine tuning for each graphic device but is independent of the number of cases.
#'@param extra_lines Numeric value (i.e. unit lines) specifying how much extra space for the annotations should be added at the bottom of the plot.
#' If annotation_date is added multiple times (e.g. for months and years) the last extra_lines value overwrites all previous ones.
#'@param text_par List of additional parameters for the text part of the annotation.
#'@param line_par List of additional parameters for the line-separator part of the annotation.
#'@param format Character string passed to [format.Date()] specifying how the date for the annotation should be formatted.
#'@param fixed_y_scale Only relevant when creating a faceted plot, e.g. with [ggplot2::facet_wrap()]. Needs to be FALSE if Y-scale is set to free.
#'
#'@export
#'@import ggplot2
#'@import rlang
#'@import scales
#'@import dplyr
#'
#'
annotation_date <- function(date_unit = "month",
                            y_percentage = 0.075,
                            extra_lines = 0,
                            text_par = list(),
                            line_par = list(),
                            format = "%Y-%m-%d",
                            fixed_y_scale = TRUE) {

  if (!is.null(format)) {
    format <- switch(date_unit,
                     week = "%ISOW",
                     month = "%b",
                     year = "%Y"
    )
  }

  params_text <- list(date_unit = date_unit,
                      format = format,
                      y_percentage = y_percentage,
                      fixed_y_scale = fixed_y_scale,
                      type = "text",
                      vjust = 0,
                      size = 4)

  params_text <- utils::modifyList(params_text, text_par)

  params_segment <- list(date_unit = date_unit,
                         format = format,
                         y_percentage = y_percentage,
                         fixed_y_scale = fixed_y_scale,
                         type = "segment",
                         text_size = params_text$size)

  params_segment <- c(params_segment, line_par)

  list(
    layer(
      data = NULL,
      geom = "text",
      stat = StatDateLabel,
      position = "identity",
      mapping = aes(y = 1,
                    label = stat(date_label)),
      params = params_text),
    layer(
      data = NULL,
      geom = "segment",
      stat = StatDateLabel,
      position = "identity",
      mapping = aes(y = 1),
      params = params_segment),
    theme(panel.spacing = unit(extra_lines, "lines"),
          plot.margin = unit(c(0, 0, extra_lines, 0), "lines")),
    coord_cartesian0(clip = "off"))
}


StatDateLabel <- ggproto("StatDateLabel", Stat,
                         required_aes = c("x"),
                         clip = "off",
                         compute_panel = function(data,
                                                  scales,
                                                  layout = layout,
                                                  na.rm = FALSE,
                                                  date_unit = NULL,
                                                  format = NULL,
                                                  y_percentage = NULL,
                                                  fixed_y_scale = NULL,
                                                  type = type,
                                                  text_size = NULL) {

                           fun <- ggplot2:::make_summary_fun(NULL, identity, sum, NULL, NULL)
                           out_dat <- ggplot2:::summarise_by_x(data, fun)
                           y_max <- out_dat %>%
                             group_by(x, PANEL) %>%
                             summarise(n = n()) %>% pull(n) %>% max

                           date_label <- data.frame(date_label = do.call(what = ISOformat,
                                                                         args = list(x = transform_time(as.Date(scales$x$range$range), date_unit),
                                                                                     format)),
                                                    date_label_year = do.call(what = ISOformat,
                                                                              args = list(x = transform_time(as.Date(scales$x$range$range), date_unit),
                                                                                          paste(format, "%Y", collapse = "")))) %>%
                             mutate(date_label_year = factor(date_label_year, unique(date_label_year))) %>%
                             group_by(date_label_year) %>%
                             summarise(n = n(),
                                       date_label = date_label[1]) %>%
                             mutate(date_label = case_when(n < max(n) / 3 ~ "",
                                                           TRUE ~ as.character(date_label)),
                                    x = cumsum(n) - n / 2 + 0.5)

                           date_label$y <- -y_max * y_percentage

                           if(type == "text") return (date_label)
                           if(nrow(date_label) == 1) return(data.frame())

                           data.frame(
                             x = cumsum(date_label$n)[-nrow(date_label)] + 0.5,
                             xend = cumsum(date_label$n)[-nrow(date_label)] + 0.5,
                             y = -y_max * y_percentage, # - 0.025 * y_max * text_size / 4,
                             yend = 0)
                         },
                         finish_layer = function(self, data, params) {
                           if (params$fixed_y_scale) data$y <- min(data$y)
                           data
                         }



)
